title: Enes Fehmi Manan 
logo: "/images/logo.png?raw=true" 
description: > 
  Data Scientist 
  <br><br>
  Statistic Student
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/enesfehmimanan/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/enesmanan">View My GitHub Profile</a> 
  <br><br>
  <a href="https://medium.com/@enesmanan768">View My Blog Website</a> 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: G-P42MEQQDWV 
